
/* This file is autogenerated by src/modules/Makefile */

#include "EST_unix.h"
#include "stdio.h"
#include "festival.h"

void festival_Lexicon_init(void);
void festival_base_init(void);
void festival_Duration_init(void);
void festival_Intonation_init(void);
void festival_Text_init(void);
void festival_UniSyn_init(void);
void festival_donovan_init(void);
void festival_parser_init(void);
void festival_UniSyn_diphone_init(void);
void festival_rxp_init(void);
void festival_clunits_init(void);
void festival_clustergen_init(void);
void festival_MultiSyn_init(void);
void festival_hts_engine_init(void);

void festival_init_modules(void)
{
   festival_Lexicon_init();
   festival_base_init();
   festival_Duration_init();
   festival_Intonation_init();
   festival_Text_init();
   festival_UniSyn_init();
   festival_donovan_init();
   festival_parser_init();
   festival_UniSyn_diphone_init();
   festival_rxp_init();
   festival_clunits_init();
   festival_clustergen_init();
   festival_MultiSyn_init();
   festival_hts_engine_init();
}

